[tools]
node = "latest"
pnpm = "latest"

[tasks.client]
run = ["cd client && pnpm run dev"]

[tasks.build]
run = ["cd client && pnpm run build"]

[tasks.deploy]
run = ["cd client && pnpm run deploy"]
